server:
  port: "3000"
  readTimeout: 10
  writeTimeout: 10

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "password"
  dbname: "dbname"
  sslmode: "disable"
  timezone: "UTC"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "superdupersecret"
  refreshSecret: "superduperrefreshsecret"

minio:
  endpoint: localhost:2087
  accessKey: 9zHbl26UppUSSDpD6nnz
  secretKey: eg5g0ByzR1NhsGw9jp40rpNpF76UnGXKygQSQm4A
  bucketName: bucket
  baseUrl: http://localhost:2087

mailer:
  host: smtp.gmail.com
  username:
  password: lefpqphfaqyjcnuk
  port: 587
  from: